### ISSUE TITLE
Sleep interval should be set dynamically

### ISSUE THREAD

**Issue by Ajedi32** [tea-drinker/saveDashie#5]
Currently this script is hardcoded to wait 11 minutes between placing pixels. In reality, the cooldown on /r/place can vary throughout the day. (I've seen it as low as 5 minutes and as high as 20.)

You should be able to extract the exact number of seconds you need to wait by inspecting the value returned from Place.draw.

**Comment by tea-drinker** [comment]
Fixed in https://github.com/tea-drinker/saveDashie/commit/318a81736b7bf26e4dbae0b3102b75f36efe6c72
